name: Build and Release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag (e.g. v1.0.0)'
        required: false
        default: ''

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev

      - name: Build release binary (Linux)
        run: |
          cargo build --release --target x86_64-unknown-linux-gnu
        working-directory: word4you-cli

      - name: Upload release artifact (Linux)
        uses: actions/upload-artifact@v4
        with:
          name: word4you-x86_64-unknown-linux-gnu
          path: word4you-cli/target/x86_64-unknown-linux-gnu/release/word4you

  build-macos:
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
          - aarch64-apple-darwin
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Add Rust targets
        run: |
          rustup target add x86_64-apple-darwin aarch64-apple-darwin

      - name: Build release binary (macOS)
        run: |
          cargo build --release --target ${{ matrix.target }}
        working-directory: word4you-cli

      - name: Upload release artifact (macOS)
        uses: actions/upload-artifact@v4
        with:
          name: word4you-${{ matrix.target }}
          path: word4you-cli/target/${{ matrix.target }}/release/word4you

  release:
    needs: [build-linux, build-macos]
    runs-on: macos-latest
    if: ${{ github.event.inputs.release_tag != '' }}
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.release_tag }}
          name: Release ${{ github.event.inputs.release_tag }}
          files: |
            dist/**/word4you*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
